### ISSUE TITLE
Java API: get player mute state and test message

### ISSUE THREAD

**Issue by car1ot** [2LSpigot/ChatSentinel#1]
Help, please... How to validate message, using ChatSentinel java api? I need this check to prevent displaying messages, because my plugin is displaying chat messages above player name.
Also could you please explain: how to check is player muted in essentialsx api?

**Comment by LinsaFTW** [comment]
Add this to the PlayerChatEvent:

if (event.isCancelled())
return;

This is not chatsentinel related tho.
